version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: settlement_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: settlement_db
      MYSQL_USER: settlement_user
      MYSQL_PASSWORD: settlement1234
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: